db.users.insert(
[{
username:'1@ufl.edu',
password: 'rleon94',
firstName:'Tod',
lastName:'Willene',
displayName:'Tod Willene',
researchinterests:'Millennium',
roles:'inactive'
}, 
{
username:'2@ufl.edu',
password: 'rleon94',
firstName:'Norman',
lastName:'Cindie',
displayName:'Norman Cindie',
researchinterests:'Fashion',
roles:'inactive'
}, 
{
username:'3@ufl.edu',
password: 'rleon94',
firstName:'Elayne',
lastName:'Zenaida',
displayName:'Elayne Zenaida',
researchinterests:'Millennium',
roles:['user'],
portfolios:[],
proficientpors:[],
provider: 'local'
}, 
{
username:'4@ufl.edu',
password: 'rleon94',
firstName:'Lauretta',
lastName:'Whitney',
displayName:'Lauretta Whitney',
researchinterests:'Educational Testing',
roles:['user'],
portfolios:[],
proficientpors:[],
provider: 'local'
}, 
{
username:'5@ufl.edu',
password: 'rleon94',
firstName:'Shawnna',
lastName:'Bryanna',
displayName:'Shawnna Bryanna',
researchinterests:'Free and Fair Trade',
roles:['user'],
portfolios:[],
proficientpors:[],
provider: 'local'
}, 
{
username:'6@ufl.edu',
password: 'rleon94',
firstName:'Linwood',
lastName:'Lora',
displayName:'Linwood Lora',
researchinterests:'Forecasting',
roles:['user'],
portfolios:[],
proficientpors:[],
provider: 'local'
}, 
{
username:'7@ufl.edu',
password: 'rleon94',
firstName:'Broderick',
lastName:'Joana',
displayName:'Broderick Joana',
researchinterests:'Medical Ethics',
roles:['user'],
portfolios:[],
proficientpors:[],
provider: 'local'
}, 
{
username:'8@ufl.edu',
password: 'rleon94',
firstName:'Natacha',
lastName:'Lazaro',
displayName:'Natacha Lazaro',
researchinterests:'Junk Food',
roles:['user'],
portfolios:[],
proficientpors:[],
provider: 'local'
}, 
{
username:'9@ufl.edu',
password: 'rleon94',
firstName:'Zena',
lastName:'Boris',
displayName:'Zena Boris',
researchinterests:'Freedom of the Press',
roles:['user'],
portfolios:[],
proficientpors:[],
provider: 'local'
}, 
{
username:'10@ufl.edu',
password: 'rleon94',
firstName:'Shawnna',
lastName:'Bryanna',
displayName:'Shawnna Bryanna',
researchinterests:'Junk Food',
roles:['user'],
portfolios:[],
proficientpors:[],
provider: 'local'
}, 
{
username:'11@ufl.edu',
password: 'rleon94',
firstName:'Hildred',
lastName:'Steffanie',
displayName:'Hildred Steffanie',
researchinterests:'Learning Disabilities',
roles:['user'],
portfolios:[],
proficientpors:[],
provider: 'local'
}, 
{
username:'12@ufl.edu',
password: 'rleon94',
firstName:'Shaquita',
lastName:'Laurene',
displayName:'Shaquita Laurene',
researchinterests:'Minors Rights',
roles:['user'],
portfolios:[],
proficientpors:[],
provider: 'local'
}, 
{
username:'13@ufl.edu',
password: 'rleon94',
firstName:'Shaquita',
lastName:'Laurene',
displayName:'Shaquita Laurene',
researchinterests:'Endangered Species',
roles:['user'],
portfolios:[],
proficientpors:[],
provider: 'local'
}, 
{
username:'14@ufl.edu',
password: 'rleon94',
firstName:'Lucinda',
lastName:'Tayna',
displayName:'Lucinda Tayna',
researchinterests:'Environment',
roles:['user'],
portfolios:[],
proficientpors:[],
provider: 'local'
}, 
{
username:'15@ufl.edu',
password: 'rleon94',
firstName:'Penni',
lastName:'Hilary',
displayName:'Penni Hilary',
researchinterests:'Labor Unions',
roles:['user'],
portfolios:[],
proficientpors:[],
provider: 'local'
}, 
{
username:'16@ufl.edu',
password: 'rleon94',
firstName:'Hildred',
lastName:'Steffanie',
displayName:'Hildred Steffanie',
researchinterests:'Endangered Species',
roles:['user'],
portfolios:[],
proficientpors:[],
provider: 'local'
}, 
{
username:'17@ufl.edu',
password: 'rleon94',
firstName:'Broderick',
lastName:'Joana',
displayName:'Broderick Joana',
researchinterests:'Environmental Protection',
roles:['user'],
portfolios:[],
proficientpors:[],
provider: 'local'
}, 
{
username:'18@ufl.edu',
password: 'rleon94',
firstName:'Racheal',
lastName:'Jene',
displayName:'Racheal Jene',
researchinterests:'Malpractice',
roles:['user'],
portfolios:[],
proficientpors:[],
provider: 'local'
}, 
{
username:'19@ufl.edu',
password: 'rleon94',
firstName:'Broderick',
lastName:'Joana',
displayName:'Broderick Joana',
researchinterests:'Fairy Tales',
roles:['user'],
portfolios:[],
proficientpors:[],
provider: 'local'
}, 
{
username:'20@ufl.edu',
password: 'rleon94',
firstName:'Altha',
lastName:'Loma',
displayName:'Altha Loma',
researchinterests:'Environmental Protection',
roles:['user'],
portfolios:[],
proficientpors:[],
provider: 'local'
}, 
{
username:'21@ufl.edu',
password: 'rleon94',
firstName:'Daniell',
lastName:'Marchele',
displayName:'Daniell Marchele',
researchinterests:'Literacy and Illiteracy',
roles:['user'],
portfolios:[],
proficientpors:[],
provider: 'local'
}, 
{
username:'22@ufl.edu',
password: 'rleon94',
firstName:'Jeanmarie',
lastName:'Samual',
displayName:'Jeanmarie Samual',
researchinterests:'Marriage',
roles:['user'],
portfolios:[],
proficientpors:[],
provider: 'local'
}, 
{
username:'23@ufl.edu',
password: 'rleon94',
firstName:'Kary',
lastName:'Felisa',
displayName:'Kary Felisa',
researchinterests:'Labor Unions',
roles:['user'],
portfolios:[],
proficientpors:[],
provider: 'local'
}, 
{
username:'24@ufl.edu',
password: 'rleon94',
firstName:'Daniell',
lastName:'Marchele',
displayName:'Daniell Marchele',
researchinterests:'Freedom of the Press',
roles:['user'],
portfolios:[],
proficientpors:[],
provider: 'local'
}, 
{
username:'25@ufl.edu',
password: 'rleon94',
firstName:'Liana',
lastName:'Trudy',
displayName:'Liana Trudy',
researchinterests:'Elections',
roles:['user'],
portfolios:[],
proficientpors:[],
provider: 'local'
}, 
{
username:'26@ufl.edu',
password: 'rleon94',
firstName:'Sherril',
lastName:'Lisandra',
displayName:'Sherril Lisandra',
researchinterests:'Minors Rights',
roles:['user'],
portfolios:[],
proficientpors:[],
provider: 'local'
}, 
{
username:'27@ufl.edu',
password: 'rleon94',
firstName:'Racheal',
lastName:'Jene',
displayName:'Racheal Jene',
researchinterests:'Free and Fair Trade',
roles:['user'],
portfolios:[],
proficientpors:[],
provider: 'local'
}, 
{
username:'28@ufl.edu',
password: 'rleon94',
firstName:'Natacha',
lastName:'Lazaro',
displayName:'Natacha Lazaro',
researchinterests:'Freedom of Speech',
privateProfile:'true',
roles:['user'],
portfolios:[],
proficientpors:[],
provider: 'local'
}, 
{
username:'29@ufl.edu',
password: 'rleon94',
firstName:'Natacha',
lastName:'Lazaro',
displayName:'Natacha Lazaro',
researchinterests:'Forecasting',
privateProfile:'true',
roles:['user'],
portfolios:[],
proficientpors:[],
provider: 'local'
}, 
{
username:'30@ufl.edu',
password: 'rleon94',
firstName:'Jeanmarie',
lastName:'Samual',
displayName:'Jeanmarie Samual',
researchinterests:'Juvenile Crime',
privateProfile:'true',
roles:['user'],
portfolios:[],
proficientpors:[],
provider: 'local'
}]
)

